#!/usr/bin/with-contenv bash
exec s6-setuidgid postgres /usr/bin/postgres -D /config/postgres \
  -c log_destination=stderr \
  -c logging_collector=off \
  -c log_line_prefix='%m [%p] %q%u@%d ' \
  -k /tmp 2>&1
