// GENERATED by scripts/exercise-media (promote) — do not edit by hand.
// Source of truth: the committed files in frontend/public/exercise-media/.
// api/tests/seed/exerciseMediaManifest.test.ts enforces both directions.

export const exerciseMedia: Record<string, { start?: string; end?: string }> = {};
