// File: api/src/seed/exercises.ts
// Curated from Wger.de (CC-BY-SA-4.0) + RP literature.
// See docs/exercise-library-curation.md before editing.

import type { ExerciseSeed } from '../schemas/exerciseSeed.js';

export const exercises: ExerciseSeed[] = [

  // ── CHEST · push_horizontal ──────────────────────────────────────────────

  {
    slug: 'barbell-bench-press',
    name: 'Barbell Bench Press',
    primary_muscle: 'chest',
    muscle_contributions: { chest: 1.0, triceps: 0.5, front_delt: 0.5 },
    movement_pattern: 'push_horizontal',
    peak_tension_length: 'mid',
    required_equipment: { _v: 1, requires: [{ type: 'barbell' }, { type: 'flat_bench' }] },
    skill_complexity: 3, loading_demand: 4, systemic_fatigue: 3,
    joint_stress_profile: { _v: 1, shoulder: 'mod', elbow: 'mod', wrist: 'mod' },
    eccentric_overload_capable: false,
    contraindications: ['shoulder_impingement'],
    requires_shoulder_flexion_overhead: false,
    loads_spine_in_flexion: false,
    loads_spine_axially: false,
    requires_hip_internal_rotation: false,
    requires_ankle_dorsiflexion: false,
    requires_wrist_extension_loaded: true,
  },

  {
    slug: 'dumbbell-bench-press',
    name: 'Dumbbell Bench Press',
    primary_muscle: 'chest',
    muscle_contributions: { chest: 1.0, triceps: 0.5, front_delt: 0.4 },
    movement_pattern: 'push_horizontal',
    peak_tension_length: 'long',
    required_equipment: {
      _v: 1,
      requires: [
        { type: 'dumbbells', min_pair_lb: 10 },
        { type: 'adjustable_bench' },
      ],
    },
    skill_complexity: 2, loading_demand: 2, systemic_fatigue: 3,
    joint_stress_profile: { _v: 1, shoulder: 'low', elbow: 'low', wrist: 'low' },
    eccentric_overload_capable: false,
    contraindications: [],
    requires_shoulder_flexion_overhead: false,
    loads_spine_in_flexion: false,
    loads_spine_axially: false,
    requires_hip_internal_rotation: false,
    requires_ankle_dorsiflexion: false,
    requires_wrist_extension_loaded: false,
  },

  {
    slug: 'incline-dumbbell-bench-press',
    name: 'Incline Dumbbell Bench Press',
    parent_slug: 'dumbbell-bench-press',
    primary_muscle: 'chest',
    muscle_contributions: { chest: 1.0, triceps: 0.4, front_delt: 0.6 },
    movement_pattern: 'push_horizontal',
    peak_tension_length: 'long',
    required_equipment: {
      _v: 1,
      requires: [
        { type: 'dumbbells', min_pair_lb: 10 },
        { type: 'adjustable_bench', incline: true },
      ],
    },
    skill_complexity: 2, loading_demand: 2, systemic_fatigue: 3,
    joint_stress_profile: { _v: 1, shoulder: 'low', elbow: 'low' },
    eccentric_overload_capable: false,
    contraindications: [],
    requires_shoulder_flexion_overhead: false,
    loads_spine_in_flexion: false,
    loads_spine_axially: false,
    requires_hip_internal_rotation: false,
    requires_ankle_dorsiflexion: false,
    requires_wrist_extension_loaded: false,
  },

  {
    slug: 'slingshot-bench-press',
    name: 'Slingshot Bench Press',
    parent_slug: 'barbell-bench-press',
    primary_muscle: 'chest',
    muscle_contributions: { chest: 1.0, triceps: 0.5, front_delt: 0.4 },
    movement_pattern: 'push_horizontal',
    peak_tension_length: 'lengthened_partial_capable',
    required_equipment: { _v: 1, requires: [{ type: 'barbell' }, { type: 'flat_bench' }] },
    skill_complexity: 3, loading_demand: 5, systemic_fatigue: 3,
    joint_stress_profile: { _v: 1, shoulder: 'low', elbow: 'low', wrist: 'mod' },
    eccentric_overload_capable: true,
    contraindications: [],
    requires_shoulder_flexion_overhead: false,
    loads_spine_in_flexion: false,
    loads_spine_axially: false,
    requires_hip_internal_rotation: false,
    requires_ankle_dorsiflexion: false,
    requires_wrist_extension_loaded: true,
  },

  // ── FRONT DELT / TRICEPS · push_vertical ─────────────────────────────────

  {
    slug: 'barbell-overhead-press-standing',
    name: 'Barbell Overhead Press (Standing)',
    primary_muscle: 'front_delt',
    muscle_contributions: { front_delt: 1.0, side_delt: 0.4, triceps: 0.5 },
    movement_pattern: 'push_vertical',
    peak_tension_length: 'mid',
    required_equipment: { _v: 1, requires: [{ type: 'barbell' }, { type: 'squat_rack' }] },
    skill_complexity: 4, loading_demand: 4, systemic_fatigue: 3,
    joint_stress_profile: { _v: 1, shoulder: 'mod', elbow: 'mod', lumbar: 'mod', wrist: 'mod' },
    eccentric_overload_capable: false,
    contraindications: ['shoulder_impingement', 'lumbar_disc'],
    requires_shoulder_flexion_overhead: true,
    loads_spine_in_flexion: false,
    loads_spine_axially: true,
    requires_hip_internal_rotation: false,
    requires_ankle_dorsiflexion: false,
    requires_wrist_extension_loaded: true,
  },

  {
    slug: 'dumbbell-shoulder-press-seated',
    name: 'Seated Dumbbell Shoulder Press',
    primary_muscle: 'front_delt',
    muscle_contributions: { front_delt: 1.0, side_delt: 0.4, triceps: 0.5 },
    movement_pattern: 'push_vertical',
    peak_tension_length: 'mid',
    required_equipment: {
      _v: 1,
      requires: [
        { type: 'dumbbells', min_pair_lb: 10 },
        { type: 'adjustable_bench', incline: true },
      ],
    },
    skill_complexity: 2, loading_demand: 2, systemic_fatigue: 2,
    joint_stress_profile: { _v: 1, shoulder: 'mod', elbow: 'low', wrist: 'low' },
    eccentric_overload_capable: false,
    contraindications: ['shoulder_impingement'],
    requires_shoulder_flexion_overhead: true,
    loads_spine_in_flexion: false,
    loads_spine_axially: false,
    requires_hip_internal_rotation: false,
    requires_ankle_dorsiflexion: false,
    requires_wrist_extension_loaded: false,
  },

  // ── SIDE DELT ─────────────────────────────────────────────────────────────

  {
    slug: 'dumbbell-lateral-raise',
    name: 'Dumbbell Lateral Raise',
    primary_muscle: 'side_delt',
    muscle_contributions: { side_delt: 1.0, front_delt: 0.2, rear_delt: 0.1 },
    movement_pattern: 'push_vertical',
    peak_tension_length: 'short',
    required_equipment: { _v: 1, requires: [{ type: 'dumbbells', min_pair_lb: 10 }] },
    skill_complexity: 1, loading_demand: 1, systemic_fatigue: 1,
    joint_stress_profile: { _v: 1, shoulder: 'mod', elbow: 'low', wrist: 'low' },
    eccentric_overload_capable: false,
    contraindications: ['shoulder_impingement'],
    requires_shoulder_flexion_overhead: false,
    loads_spine_in_flexion: false,
    loads_spine_axially: false,
    requires_hip_internal_rotation: false,
    requires_ankle_dorsiflexion: false,
    requires_wrist_extension_loaded: false,
  },

  // ── REAR DELT · pull_horizontal ──────────────────────────────────────────

  {
    slug: 'dumbbell-rear-delt-raise',
    name: 'Dumbbell Rear Delt Raise',
    primary_muscle: 'rear_delt',
    muscle_contributions: { rear_delt: 1.0, upper_back: 0.3, side_delt: 0.2 },
    movement_pattern: 'pull_horizontal',
    peak_tension_length: 'short',
    required_equipment: { _v: 1, requires: [{ type: 'dumbbells', min_pair_lb: 10 }] },
    skill_complexity: 2, loading_demand: 1, systemic_fatigue: 1,
    joint_stress_profile: { _v: 1, shoulder: 'low', elbow: 'low' },
    eccentric_overload_capable: false,
    contraindications: [],
    requires_shoulder_flexion_overhead: false,
    loads_spine_in_flexion: false,
    loads_spine_axially: false,
    requires_hip_internal_rotation: false,
    requires_ankle_dorsiflexion: false,
    requires_wrist_extension_loaded: false,
  },

  {
    slug: 'cable-face-pull',
    name: 'Cable Face Pull',
    primary_muscle: 'rear_delt',
    muscle_contributions: { rear_delt: 1.0, upper_back: 0.4, side_delt: 0.2 },
    movement_pattern: 'pull_horizontal',
    peak_tension_length: 'short',
    required_equipment: { _v: 1, requires: [{ type: 'cable_stack' }] },
    skill_complexity: 2, loading_demand: 1, systemic_fatigue: 1,
    joint_stress_profile: { _v: 1, shoulder: 'low', elbow: 'low' },
    eccentric_overload_capable: false,
    contraindications: [],
    requires_shoulder_flexion_overhead: false,
    loads_spine_in_flexion: false,
    loads_spine_axially: false,
    requires_hip_internal_rotation: false,
    requires_ankle_dorsiflexion: false,
    requires_wrist_extension_loaded: false,
  },

  // ── UPPER BACK · pull_horizontal ─────────────────────────────────────────

  {
    slug: 'chest-supported-dumbbell-row',
    name: 'Chest-Supported Dumbbell Row',
    primary_muscle: 'upper_back',
    muscle_contributions: { upper_back: 1.0, lats: 0.4, rear_delt: 0.3, biceps: 0.3 },
    movement_pattern: 'pull_horizontal',
    peak_tension_length: 'long',
    required_equipment: {
      _v: 1,
      requires: [
        { type: 'dumbbells', min_pair_lb: 10 },
        { type: 'adjustable_bench', incline: true },
      ],
    },
    skill_complexity: 2, loading_demand: 2, systemic_fatigue: 2,
    joint_stress_profile: { _v: 1, shoulder: 'low', elbow: 'low', lumbar: 'low' },
    eccentric_overload_capable: false,
    contraindications: [],
    requires_shoulder_flexion_overhead: false,
    loads_spine_in_flexion: false,
    loads_spine_axially: false,
    requires_hip_internal_rotation: false,
    requires_ankle_dorsiflexion: false,
    requires_wrist_extension_loaded: false,
  },

  {
    slug: 'barbell-bent-over-row',
    name: 'Barbell Bent-Over Row',
    primary_muscle: 'upper_back',
    muscle_contributions: { upper_back: 1.0, lats: 0.5, rear_delt: 0.3, biceps: 0.4 },
    movement_pattern: 'pull_horizontal',
    peak_tension_length: 'long',
    required_equipment: { _v: 1, requires: [{ type: 'barbell' }] },
    skill_complexity: 3, loading_demand: 4, systemic_fatigue: 3,
    joint_stress_profile: { _v: 1, shoulder: 'mod', elbow: 'low', lumbar: 'mod' },
    eccentric_overload_capable: false,
    contraindications: ['lumbar_disc'],
    requires_shoulder_flexion_overhead: false,
    loads_spine_in_flexion: true,
    loads_spine_axially: false,
    requires_hip_internal_rotation: false,
    requires_ankle_dorsiflexion: false,
    requires_wrist_extension_loaded: false,
  },

  // ── LATS · pull_vertical ─────────────────────────────────────────────────

  {
    slug: 'pullup',
    name: 'Pull-Up',
    primary_muscle: 'lats',
    muscle_contributions: { lats: 1.0, biceps: 0.5, upper_back: 0.4 },
    movement_pattern: 'pull_vertical',
    peak_tension_length: 'long',
    required_equipment: { _v: 1, requires: [{ type: 'pullup_bar' }] },
    skill_complexity: 3, loading_demand: 3, systemic_fatigue: 2,
    joint_stress_profile: { _v: 1, shoulder: 'mod', elbow: 'low' },
    eccentric_overload_capable: false,
    contraindications: ['shoulder_impingement'],
    requires_shoulder_flexion_overhead: true,
    loads_spine_in_flexion: false,
    loads_spine_axially: false,
    requires_hip_internal_rotation: false,
    requires_ankle_dorsiflexion: false,
    requires_wrist_extension_loaded: false,
  },

  {
    slug: 'lat-pulldown-machine',
    name: 'Lat Pulldown (Machine)',
    primary_muscle: 'lats',
    muscle_contributions: { lats: 1.0, biceps: 0.5, upper_back: 0.4 },
    movement_pattern: 'pull_vertical',
    peak_tension_length: 'long',
    required_equipment: { _v: 1, requires: [{ type: 'machine', name: 'lat_pulldown' }] },
    skill_complexity: 1, loading_demand: 1, systemic_fatigue: 2,
    joint_stress_profile: { _v: 1, shoulder: 'low', elbow: 'low' },
    eccentric_overload_capable: false,
    contraindications: [],
    requires_shoulder_flexion_overhead: true,
    loads_spine_in_flexion: false,
    loads_spine_axially: false,
    requires_hip_internal_rotation: false,
    requires_ankle_dorsiflexion: false,
    requires_wrist_extension_loaded: false,
  },

  // ── LATS + UPPER_BACK · pull_horizontal ──────────────────────────────────

  {
    slug: 'dumbbell-row-1arm',
    name: 'Single-Arm Dumbbell Row',
    primary_muscle: 'lats',
    muscle_contributions: { lats: 1.0, upper_back: 0.5, biceps: 0.4, rear_delt: 0.2 },
    movement_pattern: 'pull_horizontal',
    peak_tension_length: 'long',
    required_equipment: { _v: 1, requires: [{ type: 'dumbbells', min_pair_lb: 10 }] },
    skill_complexity: 2, loading_demand: 2, systemic_fatigue: 2,
    joint_stress_profile: { _v: 1, shoulder: 'low', elbow: 'low', lumbar: 'low' },
    eccentric_overload_capable: false,
    contraindications: [],
    requires_shoulder_flexion_overhead: false,
    loads_spine_in_flexion: false,
    loads_spine_axially: false,
    requires_hip_internal_rotation: false,
    requires_ankle_dorsiflexion: false,
    requires_wrist_extension_loaded: false,
  },

  // ── BICEPS ────────────────────────────────────────────────────────────────

  {
    slug: 'dumbbell-curl',
    name: 'Dumbbell Curl',
    primary_muscle: 'biceps',
    muscle_contributions: { biceps: 1.0, front_delt: 0.1 },
    movement_pattern: 'pull_vertical',
    peak_tension_length: 'mid',
    required_equipment: { _v: 1, requires: [{ type: 'dumbbells', min_pair_lb: 10 }] },
    skill_complexity: 1, loading_demand: 1, systemic_fatigue: 1,
    joint_stress_profile: { _v: 1, elbow: 'low', wrist: 'low' },
    eccentric_overload_capable: false,
    contraindications: [],
    requires_shoulder_flexion_overhead: false,
    loads_spine_in_flexion: false,
    loads_spine_axially: false,
    requires_hip_internal_rotation: false,
    requires_ankle_dorsiflexion: false,
    requires_wrist_extension_loaded: false,
  },

  {
    slug: 'dumbbell-hammer-curl',
    name: 'Dumbbell Hammer Curl',
    parent_slug: 'dumbbell-curl',
    primary_muscle: 'biceps',
    muscle_contributions: { biceps: 1.0, front_delt: 0.1 },
    movement_pattern: 'pull_vertical',
    peak_tension_length: 'mid',
    required_equipment: { _v: 1, requires: [{ type: 'dumbbells', min_pair_lb: 10 }] },
    skill_complexity: 1, loading_demand: 1, systemic_fatigue: 1,
    joint_stress_profile: { _v: 1, elbow: 'low', wrist: 'low' },
    eccentric_overload_capable: false,
    contraindications: [],
    requires_shoulder_flexion_overhead: false,
    loads_spine_in_flexion: false,
    loads_spine_axially: false,
    requires_hip_internal_rotation: false,
    requires_ankle_dorsiflexion: false,
    requires_wrist_extension_loaded: false,
  },

  // ── TRICEPS ───────────────────────────────────────────────────────────────

  {
    slug: 'dumbbell-skull-crusher',
    name: 'Dumbbell Skull Crusher',
    primary_muscle: 'triceps',
    muscle_contributions: { triceps: 1.0, front_delt: 0.1 },
    movement_pattern: 'push_horizontal',
    peak_tension_length: 'long',
    required_equipment: {
      _v: 1,
      requires: [
        { type: 'dumbbells', min_pair_lb: 10 },
        { type: 'adjustable_bench' },
      ],
    },
    skill_complexity: 2, loading_demand: 2, systemic_fatigue: 1,
    joint_stress_profile: { _v: 1, elbow: 'mod', shoulder: 'low' },
    eccentric_overload_capable: false,
    contraindications: ['elbow_tendinopathy'],
    requires_shoulder_flexion_overhead: false,
    loads_spine_in_flexion: false,
    loads_spine_axially: false,
    requires_hip_internal_rotation: false,
    requires_ankle_dorsiflexion: false,
    requires_wrist_extension_loaded: false,
  },

  {
    slug: 'cable-tricep-pressdown',
    name: 'Cable Tricep Pressdown',
    primary_muscle: 'triceps',
    muscle_contributions: { triceps: 1.0 },
    movement_pattern: 'push_vertical',
    peak_tension_length: 'short',
    required_equipment: { _v: 1, requires: [{ type: 'cable_stack' }] },
    skill_complexity: 1, loading_demand: 1, systemic_fatigue: 1,
    joint_stress_profile: { _v: 1, elbow: 'low', shoulder: 'low', wrist: 'low' },
    eccentric_overload_capable: false,
    contraindications: [],
    requires_shoulder_flexion_overhead: false,
    loads_spine_in_flexion: false,
    loads_spine_axially: false,
    requires_hip_internal_rotation: false,
    requires_ankle_dorsiflexion: false,
    requires_wrist_extension_loaded: false,
  },

  // ── QUADS · squat ─────────────────────────────────────────────────────────

  {
    slug: 'barbell-back-squat',
    name: 'Barbell Back Squat',
    primary_muscle: 'quads',
    muscle_contributions: { quads: 1.0, glutes: 0.5, hamstrings: 0.3 },
    movement_pattern: 'squat',
    peak_tension_length: 'long',
    required_equipment: { _v: 1, requires: [{ type: 'barbell' }, { type: 'squat_rack' }] },
    skill_complexity: 4, loading_demand: 4, systemic_fatigue: 5,
    joint_stress_profile: { _v: 1, knee: 'mod', lumbar: 'mod', shoulder: 'mod' },
    eccentric_overload_capable: false,
    contraindications: ['lumbar_disc', 'knee_pain'],
    requires_shoulder_flexion_overhead: false,
    loads_spine_in_flexion: false,
    loads_spine_axially: true,
    requires_hip_internal_rotation: false,
    requires_ankle_dorsiflexion: true,
    requires_wrist_extension_loaded: false,
  },

  {
    slug: 'dumbbell-goblet-squat',
    name: 'Dumbbell Goblet Squat',
    primary_muscle: 'quads',
    muscle_contributions: { quads: 1.0, glutes: 0.4, hamstrings: 0.2 },
    movement_pattern: 'squat',
    peak_tension_length: 'long',
    required_equipment: { _v: 1, requires: [{ type: 'dumbbells', min_pair_lb: 10 }] },
    skill_complexity: 2, loading_demand: 2, systemic_fatigue: 3,
    joint_stress_profile: { _v: 1, knee: 'low', lumbar: 'low' },
    eccentric_overload_capable: false,
    contraindications: [],
    requires_shoulder_flexion_overhead: false,
    loads_spine_in_flexion: false,
    loads_spine_axially: false,
    requires_hip_internal_rotation: false,
    requires_ankle_dorsiflexion: true,
    requires_wrist_extension_loaded: false,
  },

  {
    slug: 'leg-extension-machine',
    name: 'Leg Extension (Machine)',
    primary_muscle: 'quads',
    muscle_contributions: { quads: 1.0 },
    movement_pattern: 'squat',
    peak_tension_length: 'short',
    required_equipment: { _v: 1, requires: [{ type: 'machine', name: 'leg_extension' }] },
    skill_complexity: 1, loading_demand: 1, systemic_fatigue: 1,
    joint_stress_profile: { _v: 1, knee: 'mod' },
    eccentric_overload_capable: false,
    contraindications: ['knee_pain'],
    requires_shoulder_flexion_overhead: false,
    loads_spine_in_flexion: false,
    loads_spine_axially: false,
    requires_hip_internal_rotation: false,
    requires_ankle_dorsiflexion: false,
    requires_wrist_extension_loaded: false,
  },

  // ── HAMSTRINGS · hinge ────────────────────────────────────────────────────

  {
    slug: 'barbell-romanian-deadlift',
    name: 'Barbell Romanian Deadlift',
    primary_muscle: 'hamstrings',
    muscle_contributions: { hamstrings: 1.0, glutes: 0.6, upper_back: 0.3 },
    movement_pattern: 'hinge',
    peak_tension_length: 'long',
    required_equipment: { _v: 1, requires: [{ type: 'barbell' }] },
    skill_complexity: 3, loading_demand: 4, systemic_fatigue: 4,
    joint_stress_profile: { _v: 1, lumbar: 'mod', knee: 'low' },
    eccentric_overload_capable: false,
    contraindications: ['lumbar_disc'],
    requires_shoulder_flexion_overhead: false,
    loads_spine_in_flexion: true,
    loads_spine_axially: false,
    requires_hip_internal_rotation: false,
    requires_ankle_dorsiflexion: false,
    requires_wrist_extension_loaded: false,
  },

  {
    slug: 'dumbbell-romanian-deadlift',
    name: 'Dumbbell Romanian Deadlift',
    parent_slug: 'barbell-romanian-deadlift',
    primary_muscle: 'hamstrings',
    muscle_contributions: { hamstrings: 1.0, glutes: 0.5, upper_back: 0.2 },
    movement_pattern: 'hinge',
    peak_tension_length: 'long',
    required_equipment: { _v: 1, requires: [{ type: 'dumbbells', min_pair_lb: 10 }] },
    skill_complexity: 2, loading_demand: 2, systemic_fatigue: 3,
    joint_stress_profile: { _v: 1, lumbar: 'low', knee: 'low' },
    eccentric_overload_capable: false,
    contraindications: [],
    requires_shoulder_flexion_overhead: false,
    loads_spine_in_flexion: true,
    loads_spine_axially: false,
    requires_hip_internal_rotation: false,
    requires_ankle_dorsiflexion: false,
    requires_wrist_extension_loaded: false,
  },

  {
    slug: 'conventional-deadlift',
    name: 'Conventional Deadlift',
    primary_muscle: 'hamstrings',
    muscle_contributions: { hamstrings: 1.0, glutes: 0.6, upper_back: 0.5, quads: 0.3 },
    movement_pattern: 'hinge',
    peak_tension_length: 'long',
    required_equipment: { _v: 1, requires: [{ type: 'barbell' }] },
    skill_complexity: 4, loading_demand: 5, systemic_fatigue: 5,
    joint_stress_profile: { _v: 1, lumbar: 'high', knee: 'low' },
    eccentric_overload_capable: false,
    contraindications: ['lumbar_disc'],
    requires_shoulder_flexion_overhead: false,
    loads_spine_in_flexion: true,
    loads_spine_axially: true,
    requires_hip_internal_rotation: false,
    requires_ankle_dorsiflexion: false,
    requires_wrist_extension_loaded: false,
  },

  {
    slug: 'leg-curl-machine',
    name: 'Leg Curl (Machine)',
    primary_muscle: 'hamstrings',
    muscle_contributions: { hamstrings: 1.0, glutes: 0.1 },
    movement_pattern: 'hinge',
    peak_tension_length: 'long',
    required_equipment: { _v: 1, requires: [{ type: 'machine', name: 'leg_curl' }] },
    skill_complexity: 1, loading_demand: 1, systemic_fatigue: 1,
    joint_stress_profile: { _v: 1, knee: 'low', lumbar: 'low' },
    eccentric_overload_capable: false,
    contraindications: [],
    requires_shoulder_flexion_overhead: false,
    loads_spine_in_flexion: false,
    loads_spine_axially: false,
    requires_hip_internal_rotation: false,
    requires_ankle_dorsiflexion: false,
    requires_wrist_extension_loaded: false,
  },

  // ── GLUTES · squat / hinge ────────────────────────────────────────────────

  {
    slug: 'dumbbell-hip-thrust',
    name: 'Dumbbell Hip Thrust',
    primary_muscle: 'glutes',
    muscle_contributions: { glutes: 1.0, hamstrings: 0.4 },
    movement_pattern: 'hinge',
    peak_tension_length: 'short',
    required_equipment: {
      _v: 1,
      requires: [
        { type: 'dumbbells', min_pair_lb: 10 },
        { type: 'adjustable_bench' },
      ],
    },
    skill_complexity: 2, loading_demand: 2, systemic_fatigue: 2,
    joint_stress_profile: { _v: 1, lumbar: 'low', knee: 'low' },
    eccentric_overload_capable: false,
    contraindications: [],
    requires_shoulder_flexion_overhead: false,
    loads_spine_in_flexion: false,
    loads_spine_axially: false,
    requires_hip_internal_rotation: false,
    requires_ankle_dorsiflexion: false,
    requires_wrist_extension_loaded: false,
  },

  {
    slug: 'dumbbell-bulgarian-split-squat',
    name: 'Dumbbell Bulgarian Split Squat',
    primary_muscle: 'glutes',
    muscle_contributions: { glutes: 1.0, quads: 0.6, hamstrings: 0.3 },
    movement_pattern: 'squat',
    peak_tension_length: 'long',
    required_equipment: {
      _v: 1,
      requires: [
        { type: 'dumbbells', min_pair_lb: 10 },
        { type: 'adjustable_bench' },
      ],
    },
    skill_complexity: 3, loading_demand: 3, systemic_fatigue: 3,
    joint_stress_profile: { _v: 1, knee: 'mod', lumbar: 'low' },
    eccentric_overload_capable: false,
    contraindications: [],
    requires_shoulder_flexion_overhead: false,
    loads_spine_in_flexion: false,
    loads_spine_axially: false,
    requires_hip_internal_rotation: false,
    requires_ankle_dorsiflexion: false,
    requires_wrist_extension_loaded: false,
  },

  // ── LUNGE ─────────────────────────────────────────────────────────────────

  {
    slug: 'dumbbell-walking-lunge',
    name: 'Dumbbell Walking Lunge',
    primary_muscle: 'quads',
    muscle_contributions: { quads: 1.0, glutes: 0.5, hamstrings: 0.2 },
    movement_pattern: 'lunge',
    peak_tension_length: 'long',
    required_equipment: { _v: 1, requires: [{ type: 'dumbbells', min_pair_lb: 10 }] },
    skill_complexity: 2, loading_demand: 2, systemic_fatigue: 3,
    joint_stress_profile: { _v: 1, knee: 'mod', lumbar: 'low' },
    eccentric_overload_capable: false,
    contraindications: ['knee_pain'],
    requires_shoulder_flexion_overhead: false,
    loads_spine_in_flexion: false,
    loads_spine_axially: false,
    requires_hip_internal_rotation: false,
    requires_ankle_dorsiflexion: true,
    requires_wrist_extension_loaded: false,
  },

  {
    slug: 'dumbbell-reverse-lunge',
    name: 'Dumbbell Reverse Lunge',
    primary_muscle: 'quads',
    muscle_contributions: { quads: 1.0, glutes: 0.5, hamstrings: 0.2 },
    movement_pattern: 'lunge',
    peak_tension_length: 'long',
    required_equipment: { _v: 1, requires: [{ type: 'dumbbells', min_pair_lb: 10 }] },
    skill_complexity: 2, loading_demand: 2, systemic_fatigue: 2,
    joint_stress_profile: { _v: 1, knee: 'low', lumbar: 'low' },
    eccentric_overload_capable: false,
    contraindications: [],
    requires_shoulder_flexion_overhead: false,
    loads_spine_in_flexion: false,
    loads_spine_axially: false,
    requires_hip_internal_rotation: false,
    requires_ankle_dorsiflexion: false,
    requires_wrist_extension_loaded: false,
  },

  // ── CALVES ────────────────────────────────────────────────────────────────

  {
    slug: 'dumbbell-standing-calf-raise',
    name: 'Dumbbell Standing Calf Raise',
    primary_muscle: 'calves',
    muscle_contributions: { calves: 1.0 },
    movement_pattern: 'push_vertical',
    peak_tension_length: 'long',
    required_equipment: { _v: 1, requires: [{ type: 'dumbbells', min_pair_lb: 10 }] },
    skill_complexity: 1, loading_demand: 1, systemic_fatigue: 1,
    joint_stress_profile: { _v: 1, knee: 'low' },
    eccentric_overload_capable: false,
    contraindications: [],
    requires_shoulder_flexion_overhead: false,
    loads_spine_in_flexion: false,
    loads_spine_axially: false,
    requires_hip_internal_rotation: false,
    requires_ankle_dorsiflexion: false,
    requires_wrist_extension_loaded: false,
  },

  // ── CARRY ─────────────────────────────────────────────────────────────────

  {
    slug: 'dumbbell-farmers-carry',
    name: "Dumbbell Farmer's Carry",
    primary_muscle: 'upper_back',
    muscle_contributions: { upper_back: 1.0, glutes: 0.3, calves: 0.2, biceps: 0.2 },
    movement_pattern: 'carry',
    peak_tension_length: 'mid',
    required_equipment: { _v: 1, requires: [{ type: 'dumbbells', min_pair_lb: 10 }] },
    skill_complexity: 1, loading_demand: 2, systemic_fatigue: 2,
    joint_stress_profile: { _v: 1, lumbar: 'low', shoulder: 'low', wrist: 'low' },
    eccentric_overload_capable: false,
    contraindications: [],
    requires_shoulder_flexion_overhead: false,
    loads_spine_in_flexion: false,
    loads_spine_axially: true,
    requires_hip_internal_rotation: false,
    requires_ankle_dorsiflexion: false,
    requires_wrist_extension_loaded: false,
  },

  // ── ROTATION ─────────────────────────────────────────────────────────────

  {
    slug: 'cable-woodchop-high-to-low',
    name: 'Cable Wood Chop (High to Low)',
    primary_muscle: 'upper_back',
    muscle_contributions: { upper_back: 1.0, side_delt: 0.4, triceps: 0.3 },
    movement_pattern: 'rotation',
    peak_tension_length: 'mid',
    required_equipment: { _v: 1, requires: [{ type: 'cable_stack' }] },
    skill_complexity: 2, loading_demand: 2, systemic_fatigue: 2,
    joint_stress_profile: { _v: 1, shoulder: 'low', lumbar: 'low' },
    eccentric_overload_capable: false,
    contraindications: [],
    requires_shoulder_flexion_overhead: false,
    loads_spine_in_flexion: false,
    loads_spine_axially: false,
    requires_hip_internal_rotation: false,
    requires_ankle_dorsiflexion: false,
    requires_wrist_extension_loaded: false,
  },

  {
    slug: 'dumbbell-rotational-chop',
    name: 'Dumbbell Rotational Chop',
    primary_muscle: 'upper_back',
    muscle_contributions: { upper_back: 1.0, side_delt: 0.4, triceps: 0.3 },
    movement_pattern: 'rotation',
    peak_tension_length: 'mid',
    required_equipment: { _v: 1, requires: [{ type: 'dumbbells', min_pair_lb: 10 }] },
    skill_complexity: 2, loading_demand: 2, systemic_fatigue: 2,
    joint_stress_profile: { _v: 1, shoulder: 'low', lumbar: 'low' },
    eccentric_overload_capable: false,
    contraindications: [],
    requires_shoulder_flexion_overhead: false,
    loads_spine_in_flexion: false,
    loads_spine_axially: false,
    requires_hip_internal_rotation: false,
    requires_ankle_dorsiflexion: false,
    requires_wrist_extension_loaded: false,
  },

  // ── ANTI-ROTATION ─────────────────────────────────────────────────────────

  {
    slug: 'cable-pallof-press',
    name: 'Cable Pallof Press',
    primary_muscle: 'upper_back',
    muscle_contributions: { upper_back: 1.0, triceps: 0.3 },
    movement_pattern: 'anti_rotation',
    peak_tension_length: 'mid',
    required_equipment: { _v: 1, requires: [{ type: 'cable_stack' }] },
    skill_complexity: 2, loading_demand: 1, systemic_fatigue: 1,
    joint_stress_profile: { _v: 1, shoulder: 'low', lumbar: 'low' },
    eccentric_overload_capable: false,
    contraindications: [],
    requires_shoulder_flexion_overhead: false,
    loads_spine_in_flexion: false,
    loads_spine_axially: false,
    requires_hip_internal_rotation: false,
    requires_ankle_dorsiflexion: false,
    requires_wrist_extension_loaded: false,
  },

  {
    slug: 'dumbbell-overhead-carry',
    name: 'Dumbbell Overhead Carry',
    primary_muscle: 'front_delt',
    muscle_contributions: { front_delt: 1.0, side_delt: 0.4, triceps: 0.2, upper_back: 0.3 },
    movement_pattern: 'carry',
    peak_tension_length: 'mid',
    required_equipment: { _v: 1, requires: [{ type: 'dumbbells', min_pair_lb: 10 }] },
    skill_complexity: 2, loading_demand: 2, systemic_fatigue: 2,
    joint_stress_profile: { _v: 1, shoulder: 'mod', lumbar: 'low', wrist: 'low' },
    eccentric_overload_capable: false,
    contraindications: ['shoulder_impingement'],
    requires_shoulder_flexion_overhead: true,
    loads_spine_in_flexion: false,
    loads_spine_axially: true,
    requires_hip_internal_rotation: false,
    requires_ankle_dorsiflexion: false,
    requires_wrist_extension_loaded: false,
  },

  {
    slug: 'dumbbell-suitcase-carry',
    name: 'Dumbbell Suitcase Carry',
    primary_muscle: 'upper_back',
    muscle_contributions: { upper_back: 1.0, glutes: 0.2, calves: 0.1 },
    movement_pattern: 'anti_rotation',
    peak_tension_length: 'mid',
    required_equipment: { _v: 1, requires: [{ type: 'dumbbells', min_pair_lb: 10 }] },
    skill_complexity: 1, loading_demand: 1, systemic_fatigue: 1,
    joint_stress_profile: { _v: 1, lumbar: 'low', shoulder: 'low' },
    eccentric_overload_capable: false,
    contraindications: [],
    requires_shoulder_flexion_overhead: false,
    loads_spine_in_flexion: false,
    loads_spine_axially: false,
    requires_hip_internal_rotation: false,
    requires_ankle_dorsiflexion: false,
    requires_wrist_extension_loaded: false,
  },

  // ── GAIT / CARDIO ─────────────────────────────────────────────────────────

  {
    slug: 'outdoor-walking-z2',
    name: 'Outdoor Walking (Zone 2)',
    primary_muscle: 'calves',
    muscle_contributions: { calves: 1.0, glutes: 0.2, hamstrings: 0.1 },
    movement_pattern: 'gait',
    peak_tension_length: 'mid',
    required_equipment: { _v: 1, requires: [{ type: 'outdoor_walking' }] },
    skill_complexity: 1, loading_demand: 1, systemic_fatigue: 1,
    joint_stress_profile: { _v: 1, knee: 'low', lumbar: 'low' },
    eccentric_overload_capable: false,
    contraindications: [],
    requires_shoulder_flexion_overhead: false,
    loads_spine_in_flexion: false,
    loads_spine_axially: false,
    requires_hip_internal_rotation: false,
    requires_ankle_dorsiflexion: false,
    requires_wrist_extension_loaded: false,
  },

  {
    slug: 'recumbent-bike-steady-state',
    name: 'Recumbent Bike Steady-State',
    primary_muscle: 'quads',
    muscle_contributions: { quads: 1.0, hamstrings: 0.3, calves: 0.2 },
    movement_pattern: 'gait',
    peak_tension_length: 'mid',
    required_equipment: { _v: 1, requires: [{ type: 'recumbent_bike' }] },
    skill_complexity: 1, loading_demand: 1, systemic_fatigue: 1,
    joint_stress_profile: { _v: 1, knee: 'low', lumbar: 'low' },
    eccentric_overload_capable: false,
    contraindications: [],
    requires_shoulder_flexion_overhead: false,
    loads_spine_in_flexion: false,
    loads_spine_axially: false,
    requires_hip_internal_rotation: false,
    requires_ankle_dorsiflexion: false,
    requires_wrist_extension_loaded: false,
  },

];
