export const FILE_RE = /^([a-z0-9-]+)-(start|end)\.webp$/;

/**
 * Renders api/src/seed/exerciseMediaManifest.ts from the list of committed
 * webp filenames. The committed files are the source of truth; this module is
 * regenerated (never hand-edited) so the manifest can't drift from disk.
 * Entries are ALWAYS expanded (one field per line): a one-line entry is ~160
 * chars, which fails prettier printWidth 100 in api's format:check on every
 * regeneration. Prettier preserves expanded object literals, so this shape is
 * stable under `prettier --check`.
 */
export function renderManifestModule(webpFiles: string[]): string {
  const bySlug = new Map<string, { start?: string; end?: string }>();
  for (const f of [...webpFiles].sort()) {
    const m = f.match(FILE_RE);
    if (!m) throw new Error(`unexpected file in exercise-media: ${f}`);
    const [, slug, frame] = m;
    const entry = bySlug.get(slug) ?? {};
    entry[frame as 'start' | 'end'] = `/exercise-media/${slug}-${frame}.webp`;
    bySlug.set(slug, entry);
  }
  const body = [...bySlug.entries()]
    .map(([slug, media]) => {
      const fields: string[] = [];
      if (media.start) fields.push(`    start: '${media.start}',`);
      if (media.end) fields.push(`    end: '${media.end}',`);
      return `  '${slug}': {\n${fields.join('\n')}\n  },`;
    })
    .join('\n');
  const record = body ? `{\n${body}\n}` : '{}';
  return `// GENERATED by scripts/exercise-media (promote) — do not edit by hand.
// Source of truth: the committed files in frontend/public/exercise-media/.
// api/tests/seed/exerciseMediaManifest.test.ts enforces both directions.

export const exerciseMedia: Record<string, { start?: string; end?: string }> = ${record};
`;
}
